"""empty message

Revision ID: 15b6cb50e38d
Revises: 51244d14853f
Create Date: 2019-10-24 18:21:00.293772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b6cb50e38d'
down_revision = '51244d14853f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='flask_app'
    )
    op.create_index(op.f('ix_flask_app_user_email'), 'user', ['email'], unique=True, schema='flask_app')
    op.create_index(op.f('ix_flask_app_user_username'), 'user', ['username'], unique=True, schema='flask_app')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_flask_app_user_username'), table_name='user', schema='flask_app')
    op.drop_index(op.f('ix_flask_app_user_email'), table_name='user', schema='flask_app')
    op.drop_table('user', schema='flask_app')
    # ### end Alembic commands ###
