"""empty message

Revision ID: 3684854c2f86
Revises: 
Create Date: 2020-07-22 11:40:31.918563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3684854c2f86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='flask_app'
    )
    op.create_index(op.f('ix_flask_app_user_email'), 'user', ['email'], unique=True, schema='flask_app')
    op.create_index(op.f('ix_flask_app_user_username'), 'user', ['username'], unique=True, schema='flask_app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flask_app_user_username'), table_name='user', schema='flask_app')
    op.drop_index(op.f('ix_flask_app_user_email'), table_name='user', schema='flask_app')
    op.drop_table('user', schema='flask_app')
    # ### end Alembic commands ###
