"""empty message

Revision ID: 97949345ad84
Revises: fca71cd095f5
Create Date: 2021-03-06 11:07:01.503509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97949345ad84'
down_revision = 'fca71cd095f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=64), nullable=True), schema='flask_app')
    op.add_column('user', sa.Column('created_at', sa.Numeric(precision=16, scale=6), nullable=True), schema='flask_app')
    op.add_column('user', sa.Column('last_modified_at', sa.Numeric(precision=16, scale=6), nullable=True), schema='flask_app')
    op.add_column('score', sa.Column('created_at', sa.Numeric(precision=16, scale=6), nullable=True), schema='flask_app')
    op.add_column('score', sa.Column('last_modified_at', sa.Numeric(precision=16, scale=6), nullable=True), schema='flask_app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role', schema='flask_app')
    op.drop_column('user', 'created_at', schema='flask_app')
    op.drop_column('user', 'last_modified_at', schema='flask_app')
    op.drop_column('score', 'created_at', schema='flask_app')
    op.drop_column('score', 'last_modified_at', schema='flask_app')
    # ### end Alembic commands ###
