"""empty message

Revision ID: d1a0b8c1c56d
Revises: 15b6cb50e38d
Create Date: 2019-10-24 18:21:53.874429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a0b8c1c56d'
down_revision = '15b6cb50e38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='flask_app'
    )
    op.create_index(op.f('ix_flask_app_user_email'), 'user', ['email'], unique=True, schema='flask_app')
    op.create_index(op.f('ix_flask_app_user_username'), 'user', ['username'], unique=True, schema='flask_app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flask_app_user_username'), table_name='user', schema='flask_app')
    op.drop_index(op.f('ix_flask_app_user_email'), table_name='user', schema='flask_app')
    op.drop_table('user', schema='flask_app')
    # ### end Alembic commands ###
